export const ADD_INGREDIENT="ADD_INGREDIENT";
export const REMOVE_INGREDIENT="REMOVE_INGREDIENT";
export const TOTAL_COST="TOTAL_COST";


export const GET_ORDERS ="GET_ORDERS";


export const AUTHENTICATION_SUCESS ="AUTHENTICATION_SUCESS";
export const AUTHENTICATION_FAIL ="AUTHENTICATION_FAIL";

export const TOKEN_EXPIRETIME ="TOKEN_EXPIRETIME";
export const LOGOUT ="LOGOUT";

